version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8001
      - S3_URL=http://localhost:9000

  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    depends_on:
      - pgvector_db
      - s3_db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@pgvector_db:5432/vectordb
      - S3_URL=http://s3_db:9000
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  pgvector_db:
    build: ./pgvector_db
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  s3_db:
    build: ./s3_db
    volumes:
      - ./s3_db/data:/data
    ports:
      - "9000:9000"

volumes:
  pgvector_data:
