# docker-compose.yml

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8001
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - pgvector_toc
      - pgvector_manual
      - s3_db
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - S3_DB_URL=${S3_DB_URL}
      - POSTGRES_TOC_URL=postgresql://user:password@pgvector_toc:5432/tocdb
      - POSTGRES_TOC_DB=tocdb
      - POSTGRES_TOC_USER=user
      - POSTGRES_TOC_PASSWORD=password
      - POSTGRES_TOC_HOST=pgvector_toc
      - POSTGRES_TOC_PORT=5432
      - POSTGRES_MANUAL_DB=manualdb
      - POSTGRES_MANUAL_USER=user
      - POSTGRES_MANUAL_PASSWORD=password
      - POSTGRES_MANUAL_HOST=pgvector_manual
      - POSTGRES_MANUAL_PORT=5432
    ports:
      - "127.0.0.1:8001:8001"
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  pgvector_toc:
    build: ./pgvector_toc
    volumes:
      - ./pgvector_toc/init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql
      - pgvector_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_TOC_DB=tocdb
      - POSTGRES_TOC_USER=user
      - POSTGRES_TOC_PASSWORD=password
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - app-network

  pgvector_manual:
    build: ./pgvector_manual
    volumes:
      - ./pgvector_manual/init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql
      - pgvector_manual_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MANUAL_DB=manualdb
      - POSTGRES_MANUAL_USER=user
      - POSTGRES_MANUAL_PASSWORD=password
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - app-network

  s3_db:
    build: ./s3_db
    volumes:
      - ./s3_db/data:/data
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload

networks:
  app-network:
    driver: bridge

volumes:
  pgvector_data:
  pgvector_manual_data:
